project:
  type: book
#  type: website
  preview:
    port: 4200
    browser: true
  output-dir: _book # for making book things

book:
  page-navigation: true
  page-footer: "Copyright 2007-2025 Eleanor C. Sayre.  This work is licensed via [CC-BY-NC-ND](https://creativecommons.org/licenses/by-nc-nd/4.0/). Built with [Quarto](https://quarto.org/) and hosted on [github](https://github.com/esayre)."
  back-to-top-navigation: true
  downloads: pdf
  cover-image: images/handbook-cover.png
  title: "Custom blocks"
  output-file: "custom-blocks"

  chapters:
    - index.qmd

# Cross-references
crossref: 
  chapters: true
  ref-hyperlink: true

# Filters (for latexing better)
filters:
   - latex-environment  # comes from:  quarto add quarto-ext/latex-environment
#   - custom-numbered-blocks # comes from: quarto add ute/custom-numbered-blocks
   - custom-blocks # active development



# from latex-environment
environments: [ecswide,ecssidebyside]
commands: [tcblower]

# from custom-numbered-blocks
custom-numbered-blocks:
  groups:
    regbox:
      colors: [666666]
      faicon: "Bell"
#      boxstyle: foldbox.simple
#      collapse: false
#      numbered: false
    simplebox: 
      boxstyle: foldbox.simple
      collapse: false
  classes:
    casestudy:
      label: "Case study"
      group: regbox
      collapse: true
      colors: [BD33A4] # Byzantine
      listin: [cases]
      faicon: "User"
#      colors: [d999d3, a01793]
    fyi:
      label: "FYI"
      group: regbox
      colors: [1DACD6] # bright cerulean
      faicon: "Info"
    warn:
      label: "Warning"
      group: regbox
      colors: [FF8C00] # Dark orange
      faicon: "ExclamationTriangle"
    exercise:
      label: "Exercise"
      group: regbox
      collapse: true
      colors: [008B8B] # Dark cyan	
      numbered: true
      faicon: "PenNib"
    todo:
      label: "To do"
      group: simplebox
    headless:
      label: "headless"
      group: simplebox
    # Feature: default
    # todo:
    #   label: "To do"
    #   colors: [e7b1b4, 8c3236]
    #   group: default
    #   listin: [stilltodo]

format:
  html:
    theme: 
       light: 
         - yeti
         - custom.scss
       dark: 
         - superhero
         - custom.scss
    smooth-scroll: true
    css: styles.css
    toc: true
    citations-hover: true
    footnotes-hover: true
    fontsize: 11pt
    appendix-style: none
    enable-cssgrid: true
    page-layout: full
  pdf: 
    documentclass: report
    include-in-header: preamble.tex
#    include-after-body: postamble.tex
    default-image-extension: png
    cover-image: images/handbook-cover.png
    top-level-division: chapter
format-links: pdf

# Rendering choices
editor: source
freeze: auto
execute:
  echo: false
date-modified: last-modified
keep-tex: true
pdf-engine: pdflatex

# Appearance choices
callout-appearance: simple
cap-location: margin
fig-cap-location: margin
tbl-cap-location: margin
reference-location: margin #for footnotes, could be margin or document
citation-location: document #for citations
footnotes-hover: true # to hover over footnotes
title-block-banner: "/images/star-tess-dark.png"

# A unified footer with 
appendix-style: default
appendix-cite-as: display

# Authoring choices
author: 
  name: 
   given: "Eleanor C"
   family: "Sayre"